### PR TITLE
Create vuedraggble tasks

### PR DESCRIPTION
**Pull request by ryomarugon**
## Summary
Create vuedraggable tasks and display the number of tasks

## Changes 
- Create vuedraggable tasks
- Display the number of tasks
- Change the style of closing modal
  User can close modal when he click not only cancel and submit button but also outside modal-wrap

- Create switchable button （text + and - ）
   When inputTagform element(including select box and input tag to create newTag) are true, button text is "-", and when false, it is  "+"

## Related File
- TodoApp.vue
- TaskList.vue
- Modal.vue

## Remarks
-  Vuedraggble tasks
`npm install vuedraggable `
and write
`import draggable from "vuedraggable";`
to TaskList.vue
- Draggable tag  can't include v-model and has to use ` :list="tasks" `and `@update:list="tasks = $event"`
- We have to include ` <template #item="{ element }"> `inside Draggable tag

### CODE REVIEW

**Comment by aemanzano** [comment]
1. Use the index(/) instead of app (/app) 
image

2. Creating tags with the same name make you click all tags automatically
- check based on id not by name
image

3. Default tags are not shown when selecting tags
image

**Comment by aemanzano** [comment]
- Just use invert
this.inputTagForm = !this.inputTagForm
image

- you can try checking vue computed properties/watchers
image

**Comment by ryomarugon** [comment]
1. Use the index(/) instead of app (/app)

→ Fixed by changing form App.vue  to index.vue

スクリーンショット 2023-07-13 10 43 42


2. Creating tags with the same name make you click all tags automatically

→ I think same tag should be registered, so I added codes not to register same tag.
However, I'd like to hear about specification from Maki san again.

スクリーンショット 2023-07-13 11 02 02

スクリーンショット 2023-07-13 11 07 13


3. Default tags are not shown when selecting tags

 → Fixed by adding default tags to tagHistory 

スクリーンショット 2023-07-13 10 44 29

4. Just use invert this.inputTagForm = !this.inputTagForm

スクリーンショット 2023-07-13 11 02 02

5. you can try checking vue computed properties/watchers

スクリーンショット 2023-07-13 10 50 06

**Comment by aemanzano** [comment]
image

**Pull request merged**
